version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    ports:
      - 8000:8000
#    command: pytest
    command: uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000
