version: '3'
volumes:
  pgdata:
  static_files:
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - static_files:/staticfiles
    ports:
      - 8000:8000
    command: gunicorn -w 4 posts.wsgi -b 0.0.0.0:8000