name: Django CI

on:
  push:
    branches: [ indev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        ENVIRONMENT: ci
        SECRET_KEY: my-secret-key
        DEBUG: 0
        TIME_ZONE: Africa/Lagos
        ALLOWED_HOSTS: localhost
        CORS_ALLOWED_ORIGINS:
        CORS_ALLOW_ALL_ORIGINS: 0
      run: |
        python manage.py migrate
        pytest
